export const AUTO_REMARK_VARIATIONS = [
  "Hamari team customer se baat kar chuki hai, wo ye order har haal mein lena chahta hai. Is order ko aaj hi deliver karein, koi aur delay bardasht nahi hoga.",
  "Customer se rabta ho chuka hai, wo order cancel bilkul nahi karwana chahta. Ab foran is order ko deliver karein, aur intezar nahi ho sakta.",
  "Customer khud confirm kar chuka hai ke wo order lega. Delivery mein takheer ab bardasht se bahar ho chuki hai, aaj hi mamla hal karein.",
  "Hum customer se seedha baat kar chuke hain, wo order ka besabri se intezar kar raha hai. Is order ki delivery mein ab koi ozar qabool nahi.",
  "Is order ke customer se dobara baat ho chuki hai, customer ye order chahta hai, koi bahana nahi chalega. Foran response chahiye, warna hum matter management tak le jayenge.",
  "Customer se contact ho chuka hai, wo order har haal mein chahta hai. Ab aur latkana band karein, aaj hi deliver hona chahiye.",
  "Hamari team ne customer se confirm kar liya hai, wo cancel nahi karwana chahta. Customer ka sabr khatam ho chuka hai, foran action lein.",
  "Customer se baat ho chuki hai, wo apna order zaroor lena chahta hai. Apki service ki wajah se hamara business kharab ho raha hai, ise theek karein.",
  "Rabta ho chuka hai customer se, wo order besabri se lena chahta hai. Aaj ke aaj faisla ho jana chahiye, warna hum complaint escalate karenge.",
  "Team ne customer se confirm kar liya hai, order cancel karne ka koi irada nahi hai customer ka. Foran deliver karein, koi excuse nahi chalega.",
  "Customer khud keh chuka hai ke wo order lega. Ye ab qabool nahi ke order latka rahe, turant deliver karein.",
  "Hamari taraf se customer se baat ho chuki hai, wo order chahta hai. Ab koi aur takheer bardasht nahi hogi, aaj hi resolve karein.",
  "Customer se dobara confirm ho chuka hai, wo order cancel nahi karwana chahta. Delivery foran karein, warna hum ye matter management tak le jayenge.",
  "Is order ke customer ne saaf keh diya hai wo order lega. Ab bahane nahi chalenge, turant deliver karein.",
  "Customer se baat ho chuki hai, wo apna parcel lena chahta hai. Customer ka sabr khatam ho raha hai, foran response chahiye.",
  "Hamari team ne confirm kar liya hai customer se, wo order zaroor lega. Ab koi ozar qabool nahi, aaj hi delivery karein.",
  "Customer se rabta ho chuka hai, wo besabri se apna order chahta hai. Aisa dobara hua to hum aapki company se baat karenge.",
  "Team ne customer se seedha baat ki hai, wo order cancel bilkul nahi chahta. Foran deliver karein, aur delay ab nahi chalega.",
  "Customer khud confirm kar chuka hai, order zaroor lega. Delivery mein takheer ab ghair-zaroori hai, aaj hi karein.",
  "Hamari team ne customer se baat ki hai, wo order har haal mein chahta hai. Apki wajah se hamara customer kharab ho raha hai, foran theek karein.",
  "Customer se contact ho gaya hai, wo apna order chahta hai. Ab koi bahana nahi chalega, turant deliver karein.",
  "Is order ke customer se confirm ho chuka hai, wo cancel nahi chahta. Ye ab bardasht se bahar hai, foran action lein.",
  "Hum customer se baat kar chuke hain, wo order besabri se chahta hai. Warna hum is complaint ko upar tak le jayenge.",
  "Customer se dobara rabta ho chuka hai, order lena chahta hai. Aaj hi is order ka faisla hona chahiye, koi aur excuse nahi.",
  "Team ne confirm kar liya hai customer se, wo order zaroor lega. Foran deliver karein, hamara customer bohat pareshan hai.",
  "Customer khud bata chuka hai ke order lega. Ab is order mein koi delay qabool nahi, turant deliver karein.",
  "Hamari taraf se baat ho chuki hai customer se, wo order chahta hai. Ye service ka level acceptable nahi hai, foran theek karein.",
  "Customer se seedha confirm ho chuka hai, order cancel nahi hoga. Ab aur intezar nahi ho sakta, aaj hi deliver karein.",
  "Is order ke customer ne wait karne se mana nahi kiya, wo lena chahta hai. Foran deliver karein, warna hum management ko batayenge.",
  "Customer se baat ho chuki hai, wo apna order har haal mein chahta hai. Ab koi ozar nahi chalega, turant resolve karein.",
  "Hamari team ne customer se confirm liya hai, order zaroor lega. Delivery mein ab koi takheer bardasht nahi hogi.",
  "Customer khud confirm kar chuka hai order lene ka. Ye delay ab hamare business ko nuksaan pohancha raha hai, foran theek karein.",
  "Team ne customer se baat ki hai, wo order chahta hai, cancel nahi. Aaj hi ye order deliver hona chahiye.",
  "Customer se rabta ho gaya hai, wo besabri se apna parcel chahta hai. Foran action lein, warna hum complaint escalate karenge.",
  "Hamari taraf se confirm ho chuka hai, customer order zaroor lega. Ab koi bahana nahi chalega, turant deliver karein.",
  "Is order ke customer se dobara baat hui hai, wo cancel nahi karwana chahta. Delivery mein takheer ab bardasht se bahar hai.",
  "Customer khud keh chuka hai order lega. Apki wajah se customer relationship kharab ho raha hai, foran theek karein.",
  "Hamari team ne customer se contact kiya hai, wo order har haal mein chahta hai. Ab aur delay nahi chalega, aaj hi deliver karein.",
  "Customer se confirm ho chuka hai, order cancel nahi hoga. Ye ab acceptable nahi, foran response chahiye.",
  "Team ne baat ki hai customer se, wo besabri se order chahta hai. Warna hum ye matter upar tak le jayenge.",
  "Customer se rabta ho chuka hai, order zaroor lega. Aaj ke aaj is order ka faisla ho jana chahiye, koi excuse nahi.",
  "Hamari taraf se customer se baat ho chuki hai, wo cancel nahi karwana chahta. Foran deliver karein, customer ka sabr khatam ho raha hai.",
  "Is order ke customer ne confirm kar diya hai, order lega. Delivery mein ab koi ozar qabool nahi, turant karein.",
  "Customer khud confirm kar chuka hai, cancel nahi karwana. Apki service ki wajah se hamara business kharab ho raha hai.",
  "Hamari team ne dobara baat ki hai customer se, wo order chahta hai. Ab bahane nahi chalenge, aaj hi deliver karein.",
  "Customer se seedha rabta ho chuka hai, order besabri se chahta hai. Foran resolve karein, warna hum company se baat karenge.",
  "Team ne customer se confirm liya hai, wo order zaroor lega. Ye delay ab hamare liye nuksaan-deh hai, turant theek karein.",
  "Customer khud bata chuka hai order lega, cancel nahi. Ab koi takheer bardasht nahi hogi, aaj hi deliver karein.",
  "Hamari taraf se customer se contact ho chuka hai, wo order chahta hai. Foran action lein, customer bohat naraz ho raha hai.",
  "Is order ke customer se confirm ho chuka hai, order zaroor lega. Ab is mamle mein koi aur delay nahi ho sakta.",
  "Our team has already spoken to the customer and confirmed they want this order. Deliver it today — no further delay will be accepted.",
  "The customer has been contacted and refuses to cancel. Please dispatch this immediately, we cannot tolerate more delay.",
  "The customer has personally confirmed they will accept this order. This delay is unacceptable — please resolve it today.",
  "We have spoken directly to the customer and they are waiting impatiently. There is no excuse acceptable for this delay anymore.",
  "The customer does not want to cancel and is waiting for this order. We need an immediate response, or we will escalate this to your management.",
  "Contact has been made with the customer — they want this order at any cost. Stop delaying this and deliver it today.",
  "Our team has confirmed with the customer that they will not cancel. The customer's patience has run out — please take action immediately.",
  "We have spoken to the customer and they definitely want this order. Your service delay is hurting our business — please fix this.",
  "The customer has been reached and is eagerly waiting for the order. This needs to be resolved today, or we will escalate this complaint.",
  "Our team has confirmed the customer has no intention of cancelling. Deliver this immediately — no more excuses will be accepted.",
  "The customer has personally said they will take the order. This is no longer acceptable — deliver it right now.",
  "We have spoken to the customer directly and they want this order. No further delay will be tolerated — resolve this today.",
  "The customer has reconfirmed they do not want to cancel. Please deliver immediately, or we will take this up with your management.",
  "This customer has clearly stated they will accept the order. No more excuses — deliver it right away.",
  "The customer wants their parcel and has confirmed this. The customer's patience is running out — we need an immediate response.",
  "Our team has confirmed with the customer that they will definitely take the order. No more delay is acceptable — deliver today.",
  "Contact has been made and the customer is impatiently waiting for their order. If this happens again, we will take it up with your company.",
  "The team has spoken directly to the customer, who firmly does not want to cancel. Please deliver immediately, delays are no longer acceptable.",
  "The customer has personally confirmed they will take the order. This delay has become unnecessary — please resolve it today.",
  "Our team has spoken to the customer and they want this at any cost. Your delay is damaging our customer relationship — fix this now.",
  "Contact has been made with the customer and they want their order. No more excuses — deliver it immediately.",
  "The customer has confirmed and does not want to cancel this order. This is beyond acceptable now — take action immediately.",
  "We have spoken to the customer and they are impatiently waiting. If this is not resolved, we will escalate this complaint further.",
  "Contact has been re-established with the customer, who wants this order. This needs to be resolved today, no more excuses.",
  "The team has confirmed with the customer that they will definitely accept it. Please deliver immediately, our customer is very upset.",
  "The customer has personally stated they will take the order. No delay is acceptable on this anymore — deliver it right now.",
  "We have been in contact with the customer, who wants this order. This level of service is not acceptable — please fix it immediately.",
  "The customer has directly confirmed they will not cancel. No more waiting is possible — deliver this today.",
  "This customer has not refused to wait — they want the order. Deliver immediately, or we will inform your management.",
  "We have spoken to the customer and they want this order at any cost. No more excuses will be entertained — resolve this immediately.",
  "Our team has confirmed with the customer that they will definitely take it. There can be no further delay on delivery now.",
  "The customer has personally confirmed they will accept the order. This delay is now causing losses to our business — fix it immediately.",
  "The team has spoken to the customer, who wants the order and will not cancel. This order should be delivered today.",
  "Contact has been made and the customer is impatiently waiting for their parcel. Take action immediately, or we will escalate this complaint.",
  "We have re-confirmed with the customer that they will definitely take the order. No more excuses — deliver it immediately.",
  "The customer has spoken to us again and does not want to cancel. This delay has become intolerable now.",
  "The customer has personally said they will take the order. Your delay is damaging the customer relationship — fix this immediately.",
  "Our team has contacted the customer, who wants this order at any cost. No more delay is acceptable — deliver it today.",
  "The customer has confirmed and will not cancel this order. This is no longer acceptable — we need an immediate response.",
  "The team has spoken to the customer, who is impatiently waiting for the order. We will take this matter further if not resolved.",
  "Contact has been made with the customer, who will definitely take the order. Today's delivery of this order must happen, no more excuses.",
  "We have spoken directly to the customer and they will not cancel. Deliver immediately, the customer's patience is running out.",
  "This customer has confirmed they will take the order and not cancel. Delay on delivery is no longer acceptable now.",
  "The customer has personally confirmed they want it, not cancelling. Your service delay is causing losses to our business.",
  "Our team has spoken to the customer again, who wants the order. No more excuses will be accepted — deliver today.",
  "Contact has been re-established directly with the customer, who impatiently wants their parcel. Take immediate action, or we will escalate this to your company.",
  "The team has confirmed with the customer that they will definitely take it. This delay is now damaging our business — fix it immediately.",
  "The customer has personally stated they will take the order, no cancellation. No more delay can be tolerated — deliver it today.",
  "We have been in contact with the customer, who wants the order. Take immediate action, the customer is very upset now.",
  "This order's customer has confirmed and will definitely take it. There can be no further delay on this matter anymore."
];
